title: Expo Land - Выставочные стенды, наружная реклама, дизайн интерьеров
author:
  name: Expo Land
  email: 'info@expo-land.ru'
metadata:
    description: 'Expo Land - ведущий специалист по строительству выставочных стендов, наружной рекламе и дизайну интерьеров в Москве'
    keywords: 'выставочные стенды, наружная реклама, дизайн интерьеров, выставки, стенды, реклама'
    robots: 'index, follow'
    'og:type': 'website'
    'og:title': 'Expo Land - Выставочные стенды, наружная реклама, дизайн интерьеров'
    'og:description': 'Профессиональные услуги по строительству выставочных стендов, наружной рекламе и дизайну интерьеров'
    'og:url': 'https://expo-land.ru'
    'og:image': '/images/logo.png'
languages:
    supported: ['ru']
    default_lang: 'ru'
    session_store_active: false
    http_accept_language: true
    override_locale: false

