title: Эксклюзивные стенды
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1
      fields:
        content:
          type: tab
          title: PLUGIN_ADMIN.CONTENT
          fields:
            header.title:
              type: text
              autofocus: true
              style: vertical
              label: PLUGIN_ADMIN.TITLE
            content:
              type: markdown
              validate:
                type: textarea
            header.media_order:
              type: pagemedia
              label: PLUGIN_ADMIN.PAGE_MEDIA
              
        gallery:
          type: tab
          title: Галерея работ
          fields:
            header.gallery:
              type: list
              style: vertical
              label: Список работ
              help: Добавьте фотографии эксклюзивных стендов с названиями и описаниями
              collapsed: false
              btnLabel: Добавить работу
              fields:
                .title:
                  type: text
                  label: Название работы
                  placeholder: Введите название работы
                  validate:
                    required: true
                .image_upload:
                  type: file
                  label: Загрузить новое изображение
                  destination: 'user://pages/03/uslugi/01.razrabotka-stendov/03.ekskluziv'
                  multiple: false
                  limit: 1
                  filesize: 5
                  accept:
                    - .jpg
                    - .jpeg
                    - .png
                    - .gif
                    - .webp
                  help: Загрузите новое изображение стенда. Максимальный размер 5MB.
                .image_name:
                  # type: text
                  # label: Или укажите имя файла 
                  help: Альтернативно, введите имя уже загруженного файла
                .desc:
                  type: textarea
                  label: Описание (необязательно)
                  placeholder: Краткое описание работы
                  rows: 3
                  
        options:
          type: tab
          title: PLUGIN_ADMIN.OPTIONS
          fields:
            ordering:
              type: toggle
              label: PLUGIN_ADMIN.FOLDER_NUMERIC_PREFIX
              help: PLUGIN_ADMIN.FOLDER_NUMERIC_PREFIX_HELP
              highlight: 1
              options:
                1: PLUGIN_ADMIN.ENABLED
                0: PLUGIN_ADMIN.DISABLED
              validate:
                type: bool
            folder:
              type: text
              label: PLUGIN_ADMIN.FOLDER_NAME
              help: PLUGIN_ADMIN.FOLDER_NAME_HELP
              validate:
                rule: slug
            route:
              type: parents
              label: PLUGIN_ADMIN.PARENT
              classes: fancy
              validate:
                required: true
            slug:
              type: text
              label: PLUGIN_ADMIN.SLUG
              help: PLUGIN_ADMIN.SLUG_HELP
              validate:
                rule: slug
            visible:
              type: toggle
              label: PLUGIN_ADMIN.VISIBLE
              help: PLUGIN_ADMIN.VISIBLE_HELP
              highlight: 1
              options:
                1: PLUGIN_ADMIN.YES
                0: PLUGIN_ADMIN.NO
              validate:
                type: bool
            publish_date:
              type: datetime
              label: PLUGIN_ADMIN.PUBLISH_DATE
              help: PLUGIN_ADMIN.PUBLISH_DATE_HELP
              validate:
                type: datetime
            unpublish_date:
              type: datetime
              label: PLUGIN_ADMIN.UNPUBLISH_DATE
              help: PLUGIN_ADMIN.UNPUBLISH_DATE_HELP
              validate:
                type: datetime
            redirect:
              type: text
              label: PLUGIN_ADMIN.REDIRECT
              help: PLUGIN_ADMIN.REDIRECT_HELP
            page_media:
              type: pagemedia
              label: PLUGIN_ADMIN.PAGE_MEDIA 