title: PLUGIN_ADMIN.CERTIFICATES
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1
      fields:
        content:
          type: tab
          title: PLUGIN_ADMIN.CONTENT
          fields:
            header.title:
              type: text
              autofocus: true
              style: vertical
              label: PLUGIN_ADMIN.TITLE
            content:
              type: markdown
              validate:
                type: textarea
            header.media_order:
              type: pagemedia
              label: PLUGIN_ADMIN.PAGE_MEDIA
              
        certificates:
          type: tab
          title: Сертификаты
          fields:
            header.certificates:
              type: list
              style: vertical
              label: Список сертификатов
              help: Добавьте сертификаты с изображениями и описаниями
              collapsed: false
              btnLabel: Добавить сертификат
              fields:
                .title:
                  type: text
                  label: Название сертификата
                  placeholder: Введите название сертификата
                  validate:
                    required: true
                .image:
                  type: file
                  label: Изображение сертификата
                  destination: 'user/pages/02.o-kompanii/04.sertifikaty'
                  multiple: false
                  random_name: false
                  avoid_overwriting: true
                  filesize: 5
                  accept:
                    - image/*
                  help: Загрузите изображение сертификата (JPEG, PNG, WebP)
                  validate:
                    required: true
                .description:
                  type: textarea
                  label: Описание (необязательно)
                  placeholder: Краткое описание сертификата
                  rows: 3 